name = "cactus"
version = "0.1.0"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "cactus" }
description = "A tool for managing git lifecycle hooks with ✨ gleam! Pre commit, Pre push and more!"
gleam = ">= 0.34.1"
links = []
internal_modules = ["cactus/*"]
target = "erlang"

[javascript]
typescript_declarations = false
runtime = "nodejs"

[javascript.deno]
allow_all = true

[cactus.pre-commit]
actions = [
    { command = "format", kind = "sub_command", args = ["--check"] },
    { command = "test", kind = "sub_command" },
    { command = "./scripts/test.sh", kind = "binary" },
]

[cactus.pre-push]
actions = [
    { command = "format", kind = "sub_command", args = ["--check"] },
    { command = "test", kind = "sub_command" },
    { command = "./scripts/test.sh", kind = "binary" },
    { command = "go_over", kind = "module", args=["--outdated"] },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
tom = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
go_over = ">= 2.1.0 and < 3.0.0"
