name = "cactus"
version = "1.3.0"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "cactus" }
description = "A tool for managing git lifecycle hooks with ✨ gleam! Pre commit, Pre push and more!"
gleam = ">= 0.34.1"
links = []
internal_modules = ["cactus/*"]
target = "javascript"

[javascript]
typescript_declarations = false
runtime = "nodejs"

[javascript.deno]
allow_all = true

[go-over.ignore]
packages = ["gleam_hexpm"]

[cactus]
always_init = true

[cactus.pre-commit]
actions = [
    { command = "./scripts/format.sh", kind = "binary", files = [
        ".gleam",
    ] },
    { command = "./scripts/test.sh", kind = "binary" },
]

[cactus.pre-push]
actions = [
    { command = "go_over", kind = "module", args = [
        "--outdated",
    ] },
]

[cactus.test]
actions = [
    { command = "touch", kind = "binary", args = [
        ".another.test-run",
    ] },
    { command = "touch", kind = "binary", args = [
        ".test-run",
    ], files = [
        ".another.test-run",
    ] },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
tom = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleither = ">= 2.0.0 and < 3.0.0"
gxyz = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
go_over = ">= 2.1.0 and < 3.0.0"
